name: habit_hero
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  provider: ^6.0.6
  fl_chart: ^1.1.1
  shared_preferences: ^2.1.1
  flutter_slidable: ^4.0.0
  google_fonts: ^5.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
